apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-network-delay
  namespace: busybox
spec:
  schedule: "@every 10s"
  type: NetworkChaos
  networkChaos:
    action: delay
    mode: one
    selector:
      pods:
        busybox:
          - busybox-0
    delay:
      latency: "10ms"
    duration: "5s"
    direction: to
    target:
      mode: one
      selector:
        pods:
          busybox:
            - busybox-1
